version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db  
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: marketplace

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: marketplace
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"  
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:  
