# Use a slim Python image
FROM python:3.12-slim

# Install dependencies
RUN apt-get update && \
    apt-get install -y \
    gcc \
    libmariadb-dev \
    libffi-dev \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container
COPY . /app/

# Install Python dependencies
RUN pip install --no-cache-dir -r /app/requirements.txt

# Expose the port (adjust as needed)
EXPOSE 5000

# Run the application (adjust as needed)
CMD ["python", "-m", "marketplace.run"]
